apiVersion: v1
kind: Service
apiVersion: v1
kind: Namespace
metadata:
  name: prisma

---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  namespace: prisma
spec:
  ports:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4466
    protocol: TCP
  selector:
    name: prisma 
    app: prisma
    
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
  namespace: prisma
  labels:
    name: prisma 
    app: prisma
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prisma 
        app: prisma
    spec:
      containers:
        - name: prisma
          image: 'prismagraphql/prisma:1.8'
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG